name: Release Bundler

on: 
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  bundle-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # needs write permission to create a release.

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Configure Git
        run: |-
          git config --global --add advice.detachedHead 'false'
          echo "https://x-access-token:${PAT}@github.com" > ~/.git-credentials
          git config --global credential.helper 'store --file ~/.git-credentials'
        env:
          # needs a PAT granting read access to private repos
          PAT: ${{ secrets.PAT }}

      - name: Bundle source repos into release-bundle.zip
        id: bundle
        run: >-
          ./bundle.sh

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh release create ${{ github.ref_name }} \
            --title "Public Release ${{ github.ref_name }}" \
            --notes "A public release bundle from our private repositories." \
            release-bundle.zip
